name: Linting Shell Scripts

on:
  push:
    branches: [master, beta, develop]
  pull_request:
    branches: [master, beta, develop]
#   schedule:

permissions: {}

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: (Lint) Run ShellCheck
          uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # v2.0.0
          with:
            version: v0.11.0
